/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kemahasiswaan_10119006_10119022;
import java.awt.Component;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
/**
 *
 * @author minrn
 */
public class frm_utama extends javax.swing.JFrame {

    /**
     * Creates new form frm_utama
     */
    public frm_utama() {
        initComponents();
    }
    private static class JTatto extends Component {
        public JTatto() {

        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        menu_form_mahasiswa = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        menu_matkul = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        btn_nilai = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        btn_nilai_akhir = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JToolBar.Separator();
        btn_kasus = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JToolBar.Separator();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Aplikasi Kemahasiswaan_10119006_10119022");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jToolBar1.setBackground(new java.awt.Color(255, 255, 255));
        jToolBar1.setRollover(true);

        menu_form_mahasiswa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image_10119006_10119022/icons8_student_male_50px.png"))); // NOI18N
        menu_form_mahasiswa.setText("Data Mahasiswa");
        menu_form_mahasiswa.setFocusable(false);
        menu_form_mahasiswa.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        menu_form_mahasiswa.setPreferredSize(new java.awt.Dimension(107, 75));
        menu_form_mahasiswa.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        menu_form_mahasiswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_form_mahasiswaActionPerformed(evt);
            }
        });
        jToolBar1.add(menu_form_mahasiswa);
        jToolBar1.add(jSeparator3);

        menu_matkul.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image_10119006_10119022/icons8_classroom_50px.png"))); // NOI18N
        menu_matkul.setText("Data Mata Kuliah");
        menu_matkul.setFocusable(false);
        menu_matkul.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        menu_matkul.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        menu_matkul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_matkulActionPerformed(evt);
            }
        });
        jToolBar1.add(menu_matkul);
        jToolBar1.add(jSeparator1);

        btn_nilai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image_10119006_10119022/icons8_report_card_50px.png"))); // NOI18N
        btn_nilai.setText("Data Nilai Mahasiswa");
        btn_nilai.setFocusable(false);
        btn_nilai.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_nilai.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_nilai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nilaiActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_nilai);
        jToolBar1.add(jSeparator2);

        btn_nilai_akhir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image_10119006_10119022/icons8_single_page_mode_50px.png"))); // NOI18N
        btn_nilai_akhir.setText("Simulasi Nilai Akhir");
        btn_nilai_akhir.setFocusable(false);
        btn_nilai_akhir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_nilai_akhir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_nilai_akhir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nilai_akhirActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_nilai_akhir);
        jToolBar1.add(jSeparator4);

        btn_kasus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image_10119006_10119022/icons8_transaction_list_50px.png"))); // NOI18N
        btn_kasus.setText("Simulasi Kasus");
        btn_kasus.setFocusable(false);
        btn_kasus.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_kasus.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_kasus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_kasusActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_kasus);
        jToolBar1.add(jSeparator5);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Foto Pembuat ");

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image_10119006_10119022/ikhlas-022.png"))); // NOI18N

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image_10119006_10119022/ilham-006.png"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("10119006 / Ilham zaki");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("10119022 / Muhammad Ikhlas N R");

        jButton3.setBackground(new java.awt.Color(51, 153, 255));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Logout");
        jButton3.setFocusable(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image_10119006_10119022/logo-unikom.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 135, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(47, 47, 47))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(525, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(23, 23, 23))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel2)
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(21, 21, 21))
        );

        jMenu1.setText("Aplikasi Kemahasiswaan");

        jMenuItem2.setText("Tentang Pembuat");
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 637, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menu_form_mahasiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_form_mahasiswaActionPerformed
        // TODO add your handling code here:
        frm_mhs mhs = new frm_mhs();
        mhs.setVisible(true);
        
        //menghilangkan frm utama
        this.setVisible(false);
    }//GEN-LAST:event_menu_form_mahasiswaActionPerformed

    private void menu_matkulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_matkulActionPerformed
        // TODO add your handling code here:
        frm_matkul mk = new frm_matkul();
        mk.setVisible(true);
        
        //menghilangkan frm utama
        this.setVisible(false);
    }//GEN-LAST:event_menu_matkulActionPerformed

    private void btn_nilaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nilaiActionPerformed
        // TODO add your handling code here:
        frm_nilai nl = new frm_nilai();
        nl.setVisible(true);
        
        //menghilangkan frm utama
        this.setVisible(false);
    }//GEN-LAST:event_btn_nilaiActionPerformed

    private void btn_nilai_akhirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nilai_akhirActionPerformed
        // TODO add your handling code here:
        frm_nilai_akhir na = new frm_nilai_akhir();
        na.setVisible(true);
        
        //menghilangkan frm utama
        this.setVisible(false);
    }//GEN-LAST:event_btn_nilai_akhirActionPerformed

    private void btn_kasusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_kasusActionPerformed
        // TODO add your handling code here:
        frm_kasus ks = new frm_kasus();
        ks.setVisible(true);
        
        //menghilangkan frm utama
        this.setVisible(false);
    }//GEN-LAST:event_btn_kasusActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        frm_login login = new frm_login();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        frm_login login = new frm_login();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_formWindowClosed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        try {
            UIManager.setLookAndFeel("com.jtatto.plaf."
             + "aluminium.AluminiumLookAndFell");
            SwingUtilities.updateComponentTreeUI(new JTatto());
        } catch (Exception e) {
            
        }
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_utama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_kasus;
    private javax.swing.JButton btn_nilai;
    private javax.swing.JButton btn_nilai_akhir;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JToolBar.Separator jSeparator4;
    private javax.swing.JToolBar.Separator jSeparator5;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JButton menu_form_mahasiswa;
    private javax.swing.JButton menu_matkul;
    // End of variables declaration//GEN-END:variables
}
